"""revision 5

Revision ID: feb9eeecd936
Revises: 1fb7e7278d78
Create Date: 2023-08-02 12:22:09.050121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb9eeecd936'
down_revision = '1fb7e7278d78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'])
    # ### end Alembic commands ###
